---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
  - name: bosh-src
  - name: bosh-dev-release
  - name: bosh-cli

outputs:
  - name: bosh-promote-src

params:
  BLOBSTORE_ACCESS_KEY_ID: replace-me
  BLOBSTORE_SECRET_ACCESS_KEY: replace-me

run:
  path: bosh-src/ci/pipelines/promote-release/tasks/finalize-bosh-release.sh
