---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/git-resource

inputs:
  - name: bosh-src-master
  - name: bosh-src-develop

outputs:
  - name: bosh-src-merged

run:
  path: bosh-src-develop/ci/pipelines/promote-release/tasks/merge-master.sh
