---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/git-resource

inputs:
  - name: bosh-src
  - name: version

outputs:
  - name: bosh-src-tagged
run:
  path: bosh-src/ci/pipelines/stemcell/tasks/tag.sh
